name: Generate ref.json

on:
  push:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Generate
      run: |
          go run . -if ./examples/ref.json/ref.json -unsafe=true > ./examples/ref.json/ref.json.go
          cat ./examples/ref.json/ref.json.go

    - name: commit and push
      run: |
          git config --global user.email "55233766+lemon-mint@users.noreply.github.com"
          git config --global user.name "lemon-mint"
          git add .
          git commit -m "Generate ref.json `date`"
          git push 
